name: CI - Train and Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  train_and_upload_gdrive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & MLflow
        uses: actions/setup-python@v4
        with:
          python-version: '3.9-slim'
      - run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Ensure conda exists
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9-slim'
          auto-activate-base: true

      - name: Run MLflow Project (train)
        working-directory: MLProject
        run: |
          mlflow run . -e main -P input=processed/processed_data.npz -P output=artifacts -P epochs=30

      - name: Upload artifacts to Google Drive
        uses: Jumbo810/upload-github-actions-artifacts-to-google-drive@v2.3.1
        with:
          drive_service_account: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}  # set in repository secrets
          source: 'MLProject/artifacts/**'
          destination_folder: 'My-MLflow-Artifacts/CryptoForecast'
