name: CI - Train and Upload Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install MLflow (CLI)
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Ensure conda exists
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.12.7'
          auto-activate-base: true

      - name: Run MLflow Project (train)
        working-directory: MLProject
        run: |
          mlflow run . -e main -P input=processed/processed_data.npz -P output=artifacts -P epochs=2 -P batch_size=16

      - name: Upload artifacts to GitHub Actions (model + run_id)
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: MLProject/artifacts
