channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - psutil==6.1.1
  - scikit-learn==1.4.2
  - scipy==1.16.0
name: mlflow-env
