name: smsml_project

conda_env: conda.yaml  # nanti bisa diganti pakai requirements.txt

entry_points:
  main:
    parameters:
      input: {type: str}
      n_past: {type: int, default: 30}
      n_future: {type: int, default: 30}
      epochs: {type: int, default: 2}
      batch_size: {type: int, default: 32}
      units: {type: int, default: 64}
      output: {type: str, default: "artifacts"}
    command: >
      python Workflow-CI/MLProject/modelling.py --input {input} --n_past {n_past} --n_future {n_future}
      --epochs {epochs} --batch_size {batch_size} --units {units} --output {output}
